project:
  type: book
book:
  title: rtutorial
  author: Anja Heine
  date: 25.5.2025
  chapters:
  - index.qmd
  - intro.qmd
  - Templates.qmd
  - references.qmd
bibliography: references.bib
format: live-html
engine: knitr


