project:
  type: book
book:
  title: rtutorial
  author: Anja Heine
  date: 25.5.2025
  chapters:
  - index.qmd
  - intro.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
engine: knitr
editor: visual
